/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a JWT
         * @description Rate-limited per client IP, and additionally throttled per account: after several
         *     consecutive failures for one email (default 5, `LOGIN_LOCKOUT_THRESHOLD`), further
         *     attempts for that account — even with the correct password — are rejected with `429`
         *     for a lockout window (default 15 min, `LOGIN_LOCKOUT_DURATION_SECONDS`). A successful
         *     login resets the counter.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a fresh access + refresh pair
         * @description Pure-sliding session renewal. Accepts a valid, unexpired, non-revoked refresh token and
         *     returns a brand-new access token and refresh token (each with a full TTL). The presented
         *     refresh token is left valid until its own expiry — it is not rotated out. Requires no
         *     `Authorization` header (the access token may already be expired). Returns `401` for a
         *     missing/invalid/expired/revoked refresh token, if the user no longer exists, or if the
         *     token was minted before the user's most recent password change.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the bearer token (server-side denylist)
         * @description Revokes the access token carried in the `Authorization` header. If a `refreshToken` is
         *     supplied in the body, it is revoked too. The body is optional.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Change a user's password
         * @description Sets a new password for the user (minimum 10 characters). Only the password is
         *     changed; no other fields are touched. Requires the caller to be the target user,
         *     or to be ADMIN. When the caller changes their OWN password (even an admin),
         *     `currentPassword` is required and must match; an admin resetting another user's
         *     password omits it. A successful change invalidates all outstanding refresh tokens
         *     (already-issued access tokens expire naturally within their TTL).
         */
        put: operations["changeUserPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored catalog files
         * @description Lists the stored catalog-info.yaml files (shared workspace — every authenticated user
         *     sees every file).
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `name`, `namespace`, `updatedAt`. Default sort is `id`
         *       ascending; `id` ascending is always appended as a deterministic tiebreaker.
         *     - Filters (optional, whitelisted):
         *       - `name` — case- and accent-insensitive substring match against the entity name.
         *       - `namespace` — exact match (case-insensitive; namespaces are stored lowercase).
         *
         *     Each returned item includes the creator's `creatorName` resolved via join so the UI
         *     does not need an N+1 lookup.
         *
         *     Malformed query parameters (unknown sort field, out-of-range page/pageSize, repeated
         *     scalar keys) respond with `400` and a `ProblemDetail` body.
         */
        get: operations["listCatalogFiles"];
        put?: never;
        /**
         * Create a catalog file
         * @description Stores a new catalog-info.yaml document (a Backstage Component entity). The payload is
         *     validated against the Backstage descriptor format (name/namespace/tag/label/annotation
         *     grammars, entity-reference syntax for `owner`/`system`/`subcomponentOf` and the four
         *     reference arrays); references are checked for FORMAT only — resolution against other
         *     stored files is a future feature. Entity identity (namespace + name, case-insensitive)
         *     must be unique among active files; a clash is a `409`.
         */
        post: operations["createCatalogFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/cross-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cross-check every stored file's entity references
         * @description Resolves every entity reference the active files make (`owner`, `system`,
         *     `subcomponentOf`, `providesApis`, `consumesApis`, `dependsOn`, `dependencyOf`) against
         *     the workspace and reports three tiers of findings:
         *
         *     - `MISSING` (error) — the reference should resolve to a stored Component (explicit
         *       `component:` kind, or a field whose default kind is component) but no active file
         *       matches. Namespaceless references resolve within the REFERENCING file's own
         *       namespace; matching is case-insensitive throughout.
         *     - `KIND_REQUIRED` (error) — a `dependsOn`/`dependencyOf` entry without a kind; those
         *       fields have no default kind, so Backstage itself cannot ingest such a reference.
         *     - `UNVERIFIABLE` (info) — the target kind is not stored in Toadie yet (group, user,
         *       api, system, domain, …); becomes checkable as further kinds are added.
         *
         *     Findings never block saving — files legitimately reference entities that arrive later.
         */
        get: operations["crossCheckCatalogFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check one document's references against the stored files
         * @description The editor's live companion to the workspace cross-check: takes one (possibly unsaved,
         *     possibly not-yet-valid) document and returns its reference findings against the stored
         *     identities — same three-tier semantics as the workspace report. The document is
         *     sanitized but deliberately NOT validated (in-progress documents are legal here;
         *     unparsable references are skipped — the form flags them itself). A pure computation:
         *     nothing is stored; POST only because the document travels in the body. Note an unsaved
         *     file is not in the identity set, so its self-references read as missing until first
         *     save.
         */
        post: operations["checkCatalogFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Fetch a catalog file */
        get: operations["getCatalogFile"];
        /**
         * Replace a catalog file
         * @description Full replacement; same validation as create. Renaming into an identity an active file
         *     already holds is a `409`.
         */
        put: operations["replaceCatalogFile"];
        post?: never;
        /**
         * Delete a catalog file
         * @description Soft delete — the file leaves every list and read, and its identity is freed.
         */
        delete: operations["deleteCatalogFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description Short-lived access token; send as the `Authorization: Bearer` value. */
            token: string;
            /**
             * Format: int64
             * @description Access-token expiry as Unix epoch milliseconds.
             */
            expiresAt: number;
            /** @description Longer-lived token; POST to /api/v1/refresh to obtain a fresh pair. */
            refreshToken: string;
            /**
             * Format: int64
             * @description Refresh-token expiry as Unix epoch milliseconds.
             */
            refreshExpiresAt: number;
            /** Format: int32 */
            userId: number;
            /** @description Additional roles of the authenticated user — empty for a regular user. */
            roles: components["schemas"]["UserRole"][];
        };
        /**
         * @description An additional role. Every user is implicitly a regular user; the array only ever carries privileges added on top of that baseline.
         * @enum {string}
         */
        UserRole: "ADMIN";
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            /** @description Optional refresh token to revoke together with the access token. */
            refreshToken?: string;
        };
        PasswordUpdateRequest: {
            /** @description The new password (at least 10 characters, at most 71 UTF-8 bytes). */
            password: string;
            /** @description Required when the caller changes their OWN password (even an admin); omitted for an admin resetting somebody else's. */
            currentPassword?: string;
        };
        /** @description One catalog-info.yaml document — a Backstage Component entity. `kind` is implicit (`Component`) until further kinds arrive. */
        CatalogFileRequest: {
            metadata: components["schemas"]["CatalogFileMetadata"];
            spec: components["schemas"]["ComponentSpec"];
        };
        CatalogFileMetadata: {
            /** @description Entity name — unique (case-insensitively) per namespace among active files. */
            name: string;
            /**
             * @description Folded to lowercase; blank/omitted means `default`.
             * @default default
             */
            namespace: string;
            /** @description Display-only alternative to `name`; no format restrictions. */
            title?: string | null;
            description?: string | null;
            /** @description Kubernetes-style identifying key/value pairs. Keys are an optional lowercase-domain prefix (max 253 chars) plus `/` plus a name part; values follow the entity-name grammar. */
            labels?: {
                [key: string]: string;
            };
            /** @description Non-identifying key/value pairs (key grammar as labels; values free-form). Keys the catalog server writes itself (`backstage.io/managed-by-location`, `backstage.io/managed-by-origin-location`, `backstage.io/orphan`) are rejected. */
            annotations?: {
                [key: string]: string;
            };
            tags?: string[];
            links?: components["schemas"]["CatalogLink"][];
        };
        CatalogLink: {
            /** @description Absolute URI. */
            url: string;
            title?: string | null;
            /** @description Semantic icon key (entity-name grammar). */
            icon?: string | null;
        };
        ComponentSpec: {
            /** @description Component classification, e.g. `service`, `website`, `library`. */
            type: string;
            /** @description Lifecycle state, e.g. `experimental`, `production`, `deprecated`. */
            lifecycle: string;
            /** @description Entity reference `[kind:][namespace/]name` of the owning group/user (format-checked only; resolution is a future feature). */
            owner: string;
            /** @description Entity reference of the parent System. */
            system?: string | null;
            /** @description Entity reference of the parent Component. */
            subcomponentOf?: string | null;
            /** @description Entity references of provided APIs. */
            providesApis?: string[];
            /** @description Entity references of consumed APIs. */
            consumesApis?: string[];
            /** @description Entity references of Components/Resources this component depends on. */
            dependsOn?: string[];
            /** @description Entity references of Components/Resources depending on this component. */
            dependencyOf?: string[];
        };
        CatalogFileResponse: {
            /** Format: int32 */
            id: number;
            metadata: components["schemas"]["CatalogFileMetadata"];
            spec: components["schemas"]["ComponentSpec"];
            /** Format: int32 */
            createdBy: number;
            creatorName: string;
            /** @description True when the creating user has been soft-deleted. */
            creatorDeleted: boolean;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            createdAt: number;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            updatedAt: number;
        };
        CatalogFileListItem: {
            /** Format: int32 */
            id: number;
            name: string;
            namespace: string;
            title: string | null;
            type: string;
            lifecycle: string;
            owner: string;
            creatorName: string;
            /** @description True when the creating user has been soft-deleted. */
            creatorDeleted: boolean;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            updatedAt: number;
        };
        /**
         * @description MISSING and KIND_REQUIRED are errors; UNVERIFIABLE is informational (the target kind is not stored in Toadie yet).
         * @enum {string}
         */
        CrossCheckStatus: "MISSING" | "KIND_REQUIRED" | "UNVERIFIABLE";
        CrossCheckFinding: {
            /** Format: int32 */
            fileId: number;
            fileName: string;
            fileNamespace: string;
            /** @description The spec field holding the reference, e.g. `spec.dependsOn`. */
            field: string;
            reference: string;
            status: components["schemas"]["CrossCheckStatus"];
        };
        CrossCheckReport: {
            findings: components["schemas"]["CrossCheckFinding"][];
            checkedFiles: number;
            /** @description Non-blank references encountered across all checked files. */
            checkedReferences: number;
        };
        DocumentCheckFinding: {
            /** @description The spec field holding the reference, e.g. `spec.dependsOn`. */
            field: string;
            reference: string;
            status: components["schemas"]["CrossCheckStatus"];
        };
        DocumentCheckReport: {
            findings: components["schemas"]["DocumentCheckFinding"][];
        };
        CatalogFilePage: {
            items: components["schemas"]["CatalogFileListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        /** @description RFC 7807 problem detail. Served as `application/problem+json`. */
        ProblemDetail: {
            /**
             * @description A URI reference identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description URI reference of the specific occurrence (the request path). */
            instance?: string;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Caller is not permitted to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflict with an existing resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Throttled — either the per-IP rate-limit bucket is exhausted (generic detail) or, on /login, the per-account lockout is active (account-specific detail). Both carry a ProblemDetail body. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        ResourceId: number;
        /** @description 1-based page index. Defaults to 1. */
        Page: number;
        /** @description Rows per page. Defaults to 20, maximum 100. */
        PageSize: number;
        /**
         * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
         *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
         *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
         *     always appended as a deterministic tiebreaker.
         */
        Sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A fresh token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    changeUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdateRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New password shorter than 10 characters or longer than 71 UTF-8 bytes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN, or the required current password is missing/incorrect */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCatalogFiles: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /** @description Case- and accent-insensitive substring match against the entity name. */
                name?: string;
                /** @description Exact (case-insensitive) namespace match. */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of catalog files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFilePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogFileRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new catalog-file resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFileResponse"];
                };
            };
            /** @description Payload violates the descriptor-format rules */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    crossCheckCatalogFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossCheckReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    checkCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogFileRequest"];
            };
        };
        responses: {
            /** @description The document's findings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCheckReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogFileRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload violates the descriptor-format rules */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
