/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a JWT
         * @description Rate-limited per client IP, and additionally throttled per account: after several
         *     consecutive failures for one email (default 5, `LOGIN_LOCKOUT_THRESHOLD`), further
         *     attempts for that account — even with the correct password — are rejected with `429`
         *     for a lockout window (default 15 min, `LOGIN_LOCKOUT_DURATION_SECONDS`). A successful
         *     login resets the counter.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a fresh access + refresh pair
         * @description Pure-sliding session renewal. Accepts a valid, unexpired, non-revoked refresh token and
         *     returns a brand-new access token and refresh token (each with a full TTL). The presented
         *     refresh token is left valid until its own expiry — it is not rotated out. Requires no
         *     `Authorization` header (the access token may already be expired). Returns `401` for a
         *     missing/invalid/expired/revoked refresh token, if the user no longer exists, or if the
         *     token was minted before the user's most recent password change.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the bearer token (server-side denylist)
         * @description Revokes the access token carried in the `Authorization` header. If a `refreshToken` is
         *     supplied in the body, it is revoked too. The body is optional.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Change a user's password
         * @description Sets a new password for the user (minimum 10 characters). Only the password is
         *     changed; no other fields are touched. Requires the caller to be the target user,
         *     or to be ADMIN. When the caller changes their OWN password (even an admin),
         *     `currentPassword` is required and must match; an admin resetting another user's
         *     password omits it. A successful change invalidates all outstanding refresh tokens
         *     (already-issued access tokens expire naturally within their TTL).
         */
        put: operations["changeUserPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description Short-lived access token; send as the `Authorization: Bearer` value. */
            token: string;
            /**
             * Format: int64
             * @description Access-token expiry as Unix epoch milliseconds.
             */
            expiresAt: number;
            /** @description Longer-lived token; POST to /api/v1/refresh to obtain a fresh pair. */
            refreshToken: string;
            /**
             * Format: int64
             * @description Refresh-token expiry as Unix epoch milliseconds.
             */
            refreshExpiresAt: number;
            /** Format: int32 */
            userId: number;
            /** @description Additional roles of the authenticated user — empty for a regular user. */
            roles: components["schemas"]["UserRole"][];
        };
        /**
         * @description An additional role. Every user is implicitly a regular user; the array only ever carries privileges added on top of that baseline.
         * @enum {string}
         */
        UserRole: "ADMIN";
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            /** @description Optional refresh token to revoke together with the access token. */
            refreshToken?: string;
        };
        PasswordUpdateRequest: {
            /** @description The new password (at least 10 characters, at most 71 UTF-8 bytes). */
            password: string;
            /** @description Required when the caller changes their OWN password (even an admin); omitted for an admin resetting somebody else's. */
            currentPassword?: string;
        };
        /** @description RFC 7807 problem detail. Served as `application/problem+json`. */
        ProblemDetail: {
            /**
             * @description A URI reference identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description URI reference of the specific occurrence (the request path). */
            instance?: string;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Caller is not permitted to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflict with an existing resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Throttled — either the per-IP rate-limit bucket is exhausted (generic detail) or, on /login, the per-account lockout is active (account-specific detail). Both carry a ProblemDetail body. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        ResourceId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A fresh token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    changeUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdateRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New password shorter than 10 characters or longer than 71 UTF-8 bytes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN, or the required current password is missing/incorrect */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
