/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a JWT
         * @description Rate-limited per client IP, and additionally throttled per account: after several
         *     consecutive failures for one email (default 5, `LOGIN_LOCKOUT_THRESHOLD`), further
         *     attempts for that account — even with the correct password — are rejected with `429`
         *     for a lockout window (default 15 min, `LOGIN_LOCKOUT_DURATION_SECONDS`). A successful
         *     login resets the counter.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a fresh access + refresh pair
         * @description Pure-sliding session renewal. Accepts a valid, unexpired, non-revoked refresh token and
         *     returns a brand-new access token and refresh token (each with a full TTL). The presented
         *     refresh token is left valid until its own expiry — it is not rotated out. Requires no
         *     `Authorization` header (the access token may already be expired). Returns `401` for a
         *     missing/invalid/expired/revoked refresh token, if the user no longer exists, or if the
         *     token was minted before the user's most recent password change.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the bearer token (server-side denylist)
         * @description Revokes the access token carried in the `Authorization` header. If a `refreshToken` is
         *     supplied in the body, it is revoked too. The body is optional.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users (management view)
         * @description ADMIN only — the whole management surface is admin-gated; regular users keep only
         *     their self password change.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `name`, `email` (deliberately not `roles` — a set has no
         *       order). Default sort is `id` ascending; `id` ascending is always appended as a
         *       deterministic tiebreaker.
         *     - Filters (optional, whitelisted):
         *       - `name` / `email` — case- and accent-insensitive substring matches.
         *       - `role` — `ADMIN` (holders of the additional role) or `USER` (plain users).
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a user
         * @description ADMIN only. The initial password is CLIENT-generated (the SPA's 96-bit generator) and
         *     shown to the admin exactly once — the server stores only the bcrypt hash and no
         *     response ever carries plaintext. The email is canonicalized (trimmed + lowercased);
         *     a duplicate among active accounts is a `409` (a soft-deleted account frees its email).
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a user
         * @description Target user or ADMIN (guard-before-read — an unauthorized caller 403s uniformly).
         */
        get: operations["getUser"];
        /**
         * Update a user's name, email, and roles
         * @description ADMIN only. The password is deliberately not writable here (it has its own endpoint).
         *     Demoting the LAST active administrator is a `409` — the management surface must stay
         *     reachable. An email already used by another active account is also a `409`.
         */
        put: operations["updateUser"];
        post?: never;
        /**
         * Delete a user
         * @description ADMIN only, soft delete: the account can no longer sign in, outstanding refresh
         *     tokens die (`user_gone`), the email is freed for reuse, and the user's catalog files
         *     stay with a deleted-creator marker. Deleting YOURSELF is a `403`; deleting the LAST
         *     active administrator is a `409`.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Change a user's password
         * @description Sets a new password for the user (minimum 10 characters). Only the password is
         *     changed; no other fields are touched. Requires the caller to be the target user,
         *     or to be ADMIN. When the caller changes their OWN password (even an admin),
         *     `currentPassword` is required and must match; an admin resetting another user's
         *     password omits it. A successful change invalidates all outstanding refresh tokens
         *     (already-issued access tokens expire naturally within their TTL).
         */
        put: operations["changeUserPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored catalog files
         * @description Lists the stored catalog-info.yaml files (shared workspace — every authenticated user
         *     sees every file).
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `kind`, `name`, `namespace`, `updatedAt`. Default sort is
         *       `id` ascending; `id` ascending is always appended as a deterministic tiebreaker.
         *     - Filters (optional, whitelisted):
         *       - `name` — case- and accent-insensitive substring match against the entity name.
         *       - `namespace` — exact match (case-insensitive; namespaces are stored lowercase).
         *       - `kind` — one of the supported kinds (case-insensitive; unknown values are a `400`).
         *
         *     Each returned item includes the creator's `creatorName` resolved via join so the UI
         *     does not need an N+1 lookup.
         *
         *     Malformed query parameters (unknown sort field, out-of-range page/pageSize, repeated
         *     scalar keys) respond with `400` and a `ProblemDetail` body.
         */
        get: operations["listCatalogFiles"];
        put?: never;
        /**
         * Create a catalog file
         * @description Stores a new catalog-info.yaml document — a Backstage entity of any of the seven
         *     landscape kinds (Component, API, System, Domain, Resource, Group, User). The payload
         *     is validated against the Backstage descriptor format (name/namespace/tag/label/
         *     annotation grammars, entity-reference syntax, the per-kind required/forbidden field
         *     tables); references are checked for FORMAT only here — resolution is the cross-check
         *     endpoints' job and never blocks a save. The namespace must additionally be an active
         *     entry of the `namespaces` dictionary (strict — no grandfathering), else `400`.
         *     Entity identity (kind + namespace + name, case-insensitive) must be unique among
         *     active files; a clash is a `409`.
         */
        post: operations["createCatalogFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/cross-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cross-check every stored file's entity references
         * @description Resolves every entity reference the active files make (`owner`, `system`,
         *     `subcomponentOf`, `providesApis`, `consumesApis`, `dependsOn`, `dependencyOf`) against
         *     the workspace and reports three tiers of findings:
         *
         *     - `MISSING` (error) — the reference targets one of the stored kinds (Component, API,
         *       System, Domain, Resource, Group, User — explicitly or via the field's default kind)
         *       but no active file matches. Namespaceless references resolve within the REFERENCING
         *       file's own namespace; matching is case-insensitive throughout.
         *     - `KIND_REQUIRED` (error) — a `dependsOn`/`dependencyOf` entry without a kind; those
         *       fields have no default kind, so Backstage itself cannot ingest such a reference.
         *     - `UNVERIFIABLE` (info) — the target kind is not stored in Toadie (Location, Template,
         *       custom kinds).
         *
         *     Findings never block saving — files legitimately reference entities that arrive later.
         */
        get: operations["crossCheckCatalogFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check one document's references against the stored files
         * @description The editor's live companion to the workspace cross-check: takes one (possibly unsaved,
         *     possibly not-yet-valid) document and returns its reference findings against the stored
         *     identities — same three-tier semantics as the workspace report. The document is
         *     sanitized but deliberately NOT validated (in-progress documents are legal here;
         *     unparsable references are skipped — the form flags them itself). A pure computation:
         *     nothing is stored; POST only because the document travels in the body. Note an unsaved
         *     file is not in the identity set, so its self-references read as missing until first
         *     save.
         */
        post: operations["checkCatalogFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The stored files rendered together as a relationship graph
         * @description Every active file and the reference edges between them, resolved with the cross-check's
         *     semantics (per-field default kinds, namespaceless references resolve in the referencing
         *     file's own namespace, case-insensitive identity). Node statuses:
         *
         *     - `STORED` — an active catalog file (carries `fileId`).
         *     - `MISSING` — a referenced entity of a stored kind that no active file provides (the
         *       cross-check's MISSING, drawn).
         *     - `EXTERNAL` — a referenced entity of a kind Toadie doesn't store (Location, Template,
         *       custom kinds).
         *
         *     Kind-less `dependsOn`/`dependencyOf` entries (cross-check errors) are not drawable and
         *     are omitted. The optional `namespace` filter narrows which files' references are
         *     EXPANDED; targets still resolve against the whole workspace, so a stored file outside
         *     the filter appears as a STORED node when something points at it. Unpaged by design —
         *     a report-style computation over the workspace.
         */
        get: operations["getCatalogGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the workspace as structured catalog documents
         * @description Every active file as a structured document (the same shape create/replace accept),
         *     ordered by (namespace, name) case-insensitively so the export is deterministic. YAML
         *     rendering is deliberately a client concern — the SPA joins these documents into one
         *     multi-document `catalog-info.yaml` with its tested generator. Unpaged by design — a
         *     report-style read of the whole workspace.
         */
        get: operations["exportCatalogFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a batch of catalog documents (report & skip)
         * @description Imports up to 200 structured documents (the SPA parses `catalog-info.yaml` client-side
         *     and ships the parsed documents here). Each document imports INDEPENDENTLY and gets its
         *     own result row: `CREATED` (stored, `fileId` set), `INVALID` (failed the
         *     descriptor-format validation or the defined-namespace rule, `message` names the
         *     problem), `CONFLICT` (an active file
         *     already holds the kind+namespace+name identity — nothing is overwritten), or `ERROR`
         *     (an unexpected storage failure). The response is `200` even when every document failed
         *     — the result rows are the outcome; a `400` covers only the batch itself (an
         *     undecodable body or more than 200 entries).
         */
        post: operations["importCatalogFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch a catalog-info.yaml from a URL (server-side)
         * @description Retrieves the raw text at the given URL so the SPA can drop it into the import flow —
         *     server-side so any reachable host works, not only CORS-friendly ones. YAML parsing
         *     stays a client concern; this returns TEXT.
         *
         *     SSRF posture: the URL must be an absolute `https` address without credentials whose
         *     host resolves ONLY to public addresses — anything else (http, userinfo, loopback,
         *     private/link-local/unique-local ranges, unresolvable hosts) is a uniform `400` that
         *     never echoes what was probed. Redirects are not followed (`502` — use the final URL),
         *     the response body is capped at 1 MB, and upstream failures (non-200, timeout,
         *     oversize) answer `502`.
         */
        post: operations["fetchCatalogUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Fetch a catalog file */
        get: operations["getCatalogFile"];
        /**
         * Replace a catalog file
         * @description Full replacement; same validation as create (the defined-namespace rule included —
         *     strict: a file whose namespace was removed from the dictionary cannot be saved until
         *     the namespace is re-added or changed). Renaming into an identity an active file
         *     already holds is a `409`.
         */
        put: operations["replaceCatalogFile"];
        post?: never;
        /**
         * Delete a catalog file
         * @description Soft delete — the file leaves every list and read, and its identity is freed.
         */
        delete: operations["deleteCatalogFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictionaries/{dictionary}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The dictionary's URL slug. `namespaces` is the only dictionary today. */
                dictionary: "namespaces";
            };
            cookie?: never;
        };
        /**
         * Read a dictionary's entries
         * @description Any authenticated user. Returns the active entries in the admin-curated order —
         *     deliberately unpaged (a dictionary holds at most 200 entries by validation), NOT a
         *     standard list endpoint. The `namespaces` dictionary is the allowlist every
         *     catalog-file write is validated against.
         */
        get: operations["getDictionary"];
        /**
         * Replace a dictionary's entries
         * @description ADMIN only — a whole-document replace; the payload's array order becomes the stored
         *     order (there is no reorder endpoint). An item carrying an `id` renames/repositions
         *     that active entry in place (rename keeps identity); an id-less item inserts; an
         *     active entry missing from the payload is soft-deleted. Values are trimmed and folded
         *     to lowercase, and must satisfy the namespace grammar; a non-empty document must mark
         *     EXACTLY one item `isDefault` (what blank catalog-file namespaces resolve to).
         *     Swapping two values in one save is a `409` (the value uniqueness index) — rename
         *     through a temporary value in two saves.
         */
        put: operations["replaceDictionary"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description Short-lived access token; send as the `Authorization: Bearer` value. */
            token: string;
            /**
             * Format: int64
             * @description Access-token expiry as Unix epoch milliseconds.
             */
            expiresAt: number;
            /** @description Longer-lived token; POST to /api/v1/refresh to obtain a fresh pair. */
            refreshToken: string;
            /**
             * Format: int64
             * @description Refresh-token expiry as Unix epoch milliseconds.
             */
            refreshExpiresAt: number;
            /** Format: int32 */
            userId: number;
            /** @description Additional roles of the authenticated user — empty for a regular user. */
            roles: components["schemas"]["UserRole"][];
        };
        /**
         * @description An additional role. Every user is implicitly a regular user; the array only ever carries privileges added on top of that baseline.
         * @enum {string}
         */
        UserRole: "ADMIN";
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            /** @description Optional refresh token to revoke together with the access token. */
            refreshToken?: string;
        };
        UserCreateRequest: {
            name: string;
            email: string;
            /** @description Client-generated; at most 71 UTF-8 bytes (the bcrypt ceiling). Stored only as a hash and never returned. */
            password: string;
            /** @description Additional roles; omitted/empty = a regular user. */
            roles?: components["schemas"]["UserRole"][];
        };
        UserUpdateRequest: {
            name: string;
            email: string;
            roles: components["schemas"]["UserRole"][];
        };
        UserResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            email: string;
            /** @description Additional roles only — empty for a regular user. */
            roles: components["schemas"]["UserRole"][];
        };
        UserPage: {
            items: components["schemas"]["UserResponse"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        PasswordUpdateRequest: {
            /** @description The new password (at least 10 characters, at most 71 UTF-8 bytes). */
            password: string;
            /** @description Required when the caller changes their OWN password (even an admin); omitted for an admin resetting somebody else's. */
            currentPassword?: string;
        };
        /** @description One catalog-info.yaml document — a Backstage entity of one of the supported landscape kinds. `spec` is one flat superset of every kind's fields; the server enforces the per-kind required/forbidden rules (a field foreign to the kind is a 400 naming it). */
        CatalogFileRequest: {
            kind?: components["schemas"]["EntityKind"];
            metadata: components["schemas"]["CatalogFileMetadata"];
            spec: components["schemas"]["EntitySpec"];
        };
        /**
         * @description The canonical kind casing. The server accepts case-variant input and canonicalizes it on write; responses always carry the canonical form listed here.
         * @default Component
         * @enum {string}
         */
        EntityKind: "Component" | "API" | "System" | "Domain" | "Resource" | "Group" | "User";
        FetchUrlRequest: {
            /**
             * @description Absolute https URL of a catalog-info.yaml, without credentials, resolving to a public host.
             * @example https://raw.githubusercontent.com/acme/service/main/catalog-info.yaml
             */
            url: string;
        };
        FetchUrlResponse: {
            /** @description The raw text at the URL (at most 1 MB), ready for the import parser. */
            content: string;
        };
        ExportResponse: {
            /** @description The active documents, ordered by (namespace, name) case-insensitively. */
            files: components["schemas"]["CatalogFileRequest"][];
        };
        ImportRequest: {
            /** @description The documents to import, each handled independently (report & skip). */
            files: components["schemas"]["CatalogFileRequest"][];
        };
        ImportResponse: {
            /** @description One result per submitted document, in submission order. */
            results: components["schemas"]["ImportFileResult"][];
        };
        ImportFileResult: {
            /** @description The document's 0-based position in the submitted batch. */
            index: number;
            /** @description The document's (sanitized) kind — canonical-cased when recognized. */
            kind: string;
            /** @description The sanitized namespace (lowercased; blank became `default`). */
            namespace: string;
            /** @description The sanitized entity name. */
            name: string;
            /**
             * @description CREATED — stored (`fileId` set). INVALID — failed the descriptor-format validation (`message` names the rule). CONFLICT — an active file already holds this identity; nothing was overwritten. ERROR — an unexpected storage failure for this document.
             * @enum {string}
             */
            status: "CREATED" | "INVALID" | "CONFLICT" | "ERROR";
            /**
             * Format: int32
             * @description The new file's id, only when status is CREATED.
             */
            fileId?: number | null;
            /** @description The failure detail, absent on CREATED. */
            message?: string | null;
        };
        CatalogFileMetadata: {
            /** @description Entity name — unique (case-insensitively) per namespace among active files. */
            name: string;
            /** @description Folded to lowercase; blank/omitted resolves to the dictionary entry flagged as the DEFAULT at write time (none flagged → `400`). A concrete value must be an active entry of the `namespaces` dictionary (`GET /api/v1/dictionaries/namespaces`) — undefined namespaces are rejected with `400`. */
            namespace?: string;
            /** @description Display-only alternative to `name`; no format restrictions. */
            title?: string | null;
            description?: string | null;
            /** @description Kubernetes-style identifying key/value pairs. Keys are an optional lowercase-domain prefix (max 253 chars) plus `/` plus a name part; values follow the entity-name grammar. */
            labels?: {
                [key: string]: string;
            };
            /** @description Non-identifying key/value pairs (key grammar as labels; values free-form). Keys the catalog server writes itself (`backstage.io/managed-by-location`, `backstage.io/managed-by-origin-location`, `backstage.io/orphan`) are rejected. */
            annotations?: {
                [key: string]: string;
            };
            tags?: string[];
            links?: components["schemas"]["CatalogLink"][];
        };
        CatalogLink: {
            /** @description Absolute URI. */
            url: string;
            title?: string | null;
            /** @description Semantic icon key (entity-name grammar). */
            icon?: string | null;
        };
        /** @description The superset of every supported kind's spec fields — required/forbidden per kind: Component needs type/lifecycle/owner; API additionally definition; System and Domain need owner; Resource type/owner; Group type plus a PRESENT children list (may be empty); User a PRESENT memberOf list. Fields foreign to the document's kind are rejected. */
        EntitySpec: {
            /** @description Classification, e.g. `service` (Component), `openapi` (API), `team` (Group). */
            type?: string | null;
            /** @description Lifecycle state, e.g. `experimental`, `production`, `deprecated`. */
            lifecycle?: string | null;
            /** @description Entity reference `[kind:][namespace/]name` of the owning group/user (format-checked here; resolution is the cross-check's job). */
            owner?: string | null;
            /** @description Entity reference of the parent System. */
            system?: string | null;
            /** @description Entity reference of the parent Component. */
            subcomponentOf?: string | null;
            /** @description Entity references of provided APIs. */
            providesApis?: string[];
            /** @description Entity references of consumed APIs. */
            consumesApis?: string[];
            /** @description Entity references of Components/Resources this component depends on. */
            dependsOn?: string[];
            /** @description Entity references of Components/Resources depending on this component. */
            dependencyOf?: string[];
            /** @description The API definition document itself (OpenAPI/AsyncAPI/GraphQL/gRPC…). API kind only, required there. */
            definition?: string | null;
            profile?: components["schemas"]["EntityProfile"] | null;
            /** @description Entity reference of the parent Group (Group kind). */
            parent?: string | null;
            /** @description Immediate child Groups — REQUIRED (possibly empty) for Group. */
            children?: string[] | null;
            /** @description User references in this group (Group kind). */
            members?: string[];
            /** @description Group references — REQUIRED (possibly empty) for User. */
            memberOf?: string[] | null;
            /** @description Entity reference of the parent Domain (System kind). */
            domain?: string | null;
            /** @description Entity reference of the parent Domain (Domain kind). */
            subdomainOf?: string | null;
        };
        /** @description Display profile for Group/User entities. */
        EntityProfile: {
            displayName?: string | null;
            email?: string | null;
            /** @description Absolute URI of a representative image. */
            picture?: string | null;
        };
        CatalogFileResponse: {
            /** Format: int32 */
            id: number;
            kind: components["schemas"]["EntityKind"];
            metadata: components["schemas"]["CatalogFileMetadata"];
            spec: components["schemas"]["EntitySpec"];
            /** Format: int32 */
            createdBy: number;
            creatorName: string;
            /** @description True when the creating user has been soft-deleted. */
            creatorDeleted: boolean;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            createdAt: number;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            updatedAt: number;
        };
        CatalogFileListItem: {
            /** Format: int32 */
            id: number;
            kind: components["schemas"]["EntityKind"];
            name: string;
            namespace: string;
            title: string | null;
            type: string | null;
            lifecycle: string | null;
            owner: string | null;
            creatorName: string;
            /** @description True when the creating user has been soft-deleted. */
            creatorDeleted: boolean;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            updatedAt: number;
        };
        /**
         * @description MISSING and KIND_REQUIRED are errors; UNVERIFIABLE is informational (the target kind is not stored in Toadie yet).
         * @enum {string}
         */
        CrossCheckStatus: "MISSING" | "KIND_REQUIRED" | "UNVERIFIABLE";
        CrossCheckFinding: {
            /** Format: int32 */
            fileId: number;
            fileName: string;
            fileNamespace: string;
            /** @description The spec field holding the reference, e.g. `spec.dependsOn`. */
            field: string;
            reference: string;
            status: components["schemas"]["CrossCheckStatus"];
        };
        CrossCheckReport: {
            findings: components["schemas"]["CrossCheckFinding"][];
            checkedFiles: number;
            /** @description Non-blank references encountered across all checked files. */
            checkedReferences: number;
        };
        DocumentCheckFinding: {
            /** @description The spec field holding the reference, e.g. `spec.dependsOn`. */
            field: string;
            reference: string;
            status: components["schemas"]["CrossCheckStatus"];
        };
        DocumentCheckReport: {
            findings: components["schemas"]["DocumentCheckFinding"][];
        };
        /** @enum {string} */
        GraphNodeStatus: "STORED" | "MISSING" | "EXTERNAL";
        GraphNode: {
            /** @description Canonical lowercased identity `kind:namespace/name` (the dedupe key). */
            id: string;
            kind: string;
            namespace: string;
            name: string;
            title?: string | null;
            /**
             * Format: int32
             * @description The backing file for STORED nodes; null for virtual nodes.
             */
            fileId?: number | null;
            status: components["schemas"]["GraphNodeStatus"];
        };
        GraphEdge: {
            sourceId: string;
            targetId: string;
            /** @description The spec field the reference lives in, e.g. `spec.dependsOn`. */
            field: string;
        };
        CatalogGraph: {
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        CatalogFilePage: {
            items: components["schemas"]["CatalogFileListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        DictionaryEntry: {
            /** Format: int32 */
            id: number;
            /** @description Stored lowercase-folded (the namespace grammar). */
            value: string;
            /** @description Exactly one entry per (non-empty) dictionary carries this — for `namespaces` it is what a blank/omitted catalog-file namespace resolves to. */
            isDefault: boolean;
        };
        DictionaryEntryList: {
            /** @description Active entries in the admin-curated order. */
            items: components["schemas"]["DictionaryEntry"][];
        };
        DictionaryEntryInput: {
            /**
             * Format: int32
             * @description Present = update that active entry in place; absent = insert a new one.
             */
            id?: number | null;
            /** @description Trimmed and folded to lowercase before validation and storage. */
            value: string;
            /**
             * @description A non-empty document must flag EXACTLY one item (zero or several is a `400`).
             * @default false
             */
            isDefault: boolean;
        };
        DictionaryUpdateRequest: {
            /** @description The full replacement document — array order becomes the stored order. */
            items: components["schemas"]["DictionaryEntryInput"][];
        };
        /** @description RFC 7807 problem detail. Served as `application/problem+json`. */
        ProblemDetail: {
            /**
             * @description A URI reference identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description URI reference of the specific occurrence (the request path). */
            instance?: string;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Caller is not permitted to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflict with an existing resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Throttled — either the per-IP rate-limit bucket is exhausted (generic detail) or, on /login, the per-account lockout is active (account-specific detail). Both carry a ProblemDetail body. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The upstream request made on the caller's behalf failed (the remote answered non-200, redirected, timed out, or exceeded the size cap). */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        ResourceId: number;
        /** @description 1-based page index. Defaults to 1. */
        Page: number;
        /** @description Rows per page. Defaults to 20, maximum 100. */
        PageSize: number;
        /**
         * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
         *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
         *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
         *     always appended as a deterministic tiebreaker.
         */
        Sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A fresh token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                name?: string;
                email?: string;
                role?: "ADMIN" | "USER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new user resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation error (blank/too-long name or email, password rules) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN, or attempted to delete their own account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    changeUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdateRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New password shorter than 10 characters or longer than 71 UTF-8 bytes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN, or the required current password is missing/incorrect */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCatalogFiles: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /** @description Case- and accent-insensitive substring match against the entity name. */
                name?: string;
                /** @description Exact (case-insensitive) namespace match. */
                namespace?: string;
                /** @description One of the supported kinds (case-insensitive); unknown values are a 400. */
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of catalog files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFilePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogFileRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new catalog-file resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFileResponse"];
                };
            };
            /** @description Payload violates the descriptor-format rules */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    crossCheckCatalogFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossCheckReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    checkCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogFileRequest"];
            };
        };
        responses: {
            /** @description The document's findings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCheckReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCatalogGraph: {
        parameters: {
            query?: {
                /** @description Exact (case-insensitive) namespace of the files to expand. */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogGraph"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exportCatalogFiles: {
        parameters: {
            query?: {
                /** @description Exact (case-insensitive) namespace of the files to export. */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    importCatalogFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description One result per submitted document, in order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    fetchCatalogUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchUrlRequest"];
            };
        };
        responses: {
            /** @description The raw text at the URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
            502: components["responses"]["BadGateway"];
        };
    };
    getCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogFileRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload violates the descriptor-format rules */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCatalogFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The dictionary's URL slug. `namespaces` is the only dictionary today. */
                dictionary: "namespaces";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryEntryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The dictionary's URL slug. `namespaces` is the only dictionary today. */
                dictionary: "namespaces";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictionaryUpdateRequest"];
            };
        };
        responses: {
            /** @description Replaced */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
